import type { Metadata } from "next";
import { Poppins, Cal_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ModalProvider } from "@/context/ModalContext";
import Navbar from "@/components/Navbar/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const calSans = Cal_Sans({
  variable: "--font-calSans",
  weight: ["400"],
});

const apercuBlack = localFont({
  src: "../public/fonts/Apercu-Pro-Black.ttf",
  variable: "--font-apercu-black",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${calSans.variable} ${apercuBlack.variable} antialiased ${poppins.className}`}
      >
        <ModalProvider>
          <Navbar />
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}
