import type { Metadata } from "next";
import { Poppins, Cal_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ModalProvider } from "@/context/ModalContext";
import Navbar from "@/components/Navbar/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const calSans = Cal_Sans({
  variable: "--font-calSans",
  weight: ["400"],
});

const apercuBlack = localFont({
  src: "../public/fonts/Apercu-Pro-Black.ttf",
  variable: "--font-apercu-black",
});

const apercuBold = localFont({
  src: '../public/fonts/apercu_bold_pro.otf',
  variable: "--font-apercu-bold"
})

const apercuRegular = localFont({
  src: '../public/fonts/apercu_regular_pro.otf',
  variable: '--font-apercu-regular'
})

const apercuItallic = localFont({
  src: '../public/fonts/apercu_regular_italic_pro.otf',
  variable: '--font-apercu-itallic'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${calSans.variable} ${apercuBlack.variable} ${apercuBold.variable} ${apercuRegular.variable} ${apercuItallic.variable} antialiased ${poppins.className}`}
      >
        <ModalProvider>
          <Navbar />
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}
